language: "go"

matrix:
  allow_failures:
  - go: tip

go:
  - "1.10"
  - tip

script:
  - touch .env
  - make test ARGS='-coverprofile=coverage.txt -covermode=atomic'
  - make lint-warn

after_success:
  - bash <(curl -s https://codecov.io/bash)
