language: "go"

matrix:
  allow_failures:
  - go: tip

env:
  - GO111MODULE=on

go:
  - "1.11"
  - tip

script:
  - touch .env
  - go mod download
  - go mod vendor
  - make test ARGS='-v -race -count=2 -coverprofile=coverage.txt -covermode=atomic ./...'
  - make lint-warn

after_success:
  - bash <(curl -s https://codecov.io/bash)
