language: "go"

matrix:
  allow_failures:
  - go: tip

go:
  - "1.10"
  - tip

script:
  - touch .env
  - make test ARGS='-coverprofile=coverage.txt -covermode=atomic'"
  - gometalinter.v2 --enable-all --disable=vetshadow --disable=gocyclo --disable=unparm --disable=nakedret --disable=lll --disable=dupl --disable=test --deadline=120s
  - gometalinter.v2 --disable-all --enable=vetshadow --enable=gocyclo --enable=unparm --enable=nakedret --enable=lll --enable=dupl --enable=test --deadline=120s || true

after_success:
  - bash <(curl -s https://codecov.io/bash)
