name: Testing

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - run: go version
      - name: Run tidy
        run: make tidy
      - name: Run fmt
        run: go fmt ./...
      - name: Fail if changes
        run: git diff-index --exit-code HEAD
      - name: Run linter
        run: make lint
      - name: Run tests
        run: make test
        env:
          SKIP_LINT: 1
